s="hello python"
print(s.capitalize())
print(s.upper())
print(s.lower())
print(s.count('l'))
print(s.find('l'))  
print(s.center(20,'z'))
print('hello\thi')
print('hello\thi'.expandtabs())
print(s.isalnum())
print(s.isalpha())
print(s.islower())
print(s.isspace())
print(s.istitle())
print(s[-1]=='n')
print(s.split('o'))
print(s.partition('t'))